### ISSUE TITLE
CNI integration issue for AWS K8s clusters

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/mizar-mp#16]
The networking namespace passed from k8s to mizarmp-CNI is “/proc/14705/ns/net”, which is in the format of “/proc/PID/ns/net”. It is based on AWS container runtime. It is unique and it is an acceptable format. Unfortunately, the current approach of taking only the last part of the string (that is “net”) will not work because:
1.	It is not unique for different endpoints running on the same host
2.	It doesn’t align with the ip netns format with our initial thinking based on our familiar container runtimes

**Comment by er1cthe0ne** [comment]
fixed in commit: 99e1cb1e0fb44e6b650a1ca180f29e4ccad3d978
